spring:
  application:
    name: user-service

default:
  # real-server-url: server
  # mock-server-url: mock-server

#eureka:
#  instance:
#    instance-id: gi
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://127.0.0.1:8761/eureka
